name: agriapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  badges: ^3.1.2
  easy_stepper: ^0.8.4
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
